name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: git config --global --add safe.directory /github/workspace
    - name: Check out TILs
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: wzieba/til
    - name: Append TILs
      uses: wzieba/github-action-til-autoformat-readme@9ace979f6de88a5692e6361f927aa27eb656a706
      with:
        repo_name: 'wzieba/til'
        presentation: 'table'
        list_most_recent: 60
        tils_counter_format: ''
        date_format: '02/01/2006'
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        path: medium
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r medium/requirements.txt
    - name: Update README
      run: |-
        cd medium
        python main.py
        cat README.md
    - name: Commit and push if changed
      run: |-
        cd medium
        echo "TILs"
        cat ../README.md
        echo "Blog"
        cat README.md
        cat ../README.md >> README.md
        echo "Joined"
        cat README.md
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update README.md"
        git push

